### PR TITLE
Refactor to sealed classes

### PR DESCRIPTION
**Pull request by nschwermann**
It shouldn't be possible to create SimpleTrollNumbers that are not 1,2,3,4 or 16. Refactoring to a sealed class prohibits users from doing so. Perfect usecase and example for kotlin sealed classes as algebraic data types. Thanks for the reminder that I need to read Discworld!

### CODE REVIEW

**Comment by nschwermann** [comment]
Holler if your are interested

**Comment by nschwermann** [comment]
I closed cause I cleaned up history on my side, didn't realize I was commiting with wrong email. If you would like me to reopen the PR just let me know! Or you can potentially cherry pick my fix for your + issue.
Regards

**Comment by uzilan** [comment]
@nschwermann - maybe you could create a new PR?

**Comment by nschwermann** [comment]
@uzilan sure thanks for your interest. I have opened a new PR.

**Pull request closed without merging**
